### PR TITLE
feat: retry to bind to different port when port in use

### PR DESCRIPTION
**Pull request by mint-dewit**
This should fix potential connection issues arising due to #23

### CODE REVIEW

**Comment by haakonnessjoen** [comment]
I am probably stupid for asking. But can't you just remove the port argument from bind() I thought node tried to give you a random port automatically?

```Call socket.bind if you want to receive datagrams. socket.bind() will bind to the "all interfaces" address on a random port (it does the right thing for both udp4 and udp6 sockets). You can then retrieve the address and port with socket.address().address and socket.address().port.```

**Comment by mint-dewit** [comment]
I hadn't thought of it, to be honest. Do you happen to know if that will always give a free port too?

**Comment by haakonnessjoen** [comment]
Old documentation saying "it does the right thing", and new documentation not mentioning random problems with binding to taken ports sure hints to it though.

Also, in the source of dgram in Node, if you try to send data without binding first, it automatically does: 

```
if (state.bindState === BIND_STATE_UNBOUND)
    this.bind({ port: 0, exclusive: true }, null);
```

And I think they/we would see a lot of issue requests if people would randomly get "port already in use" errors when just sending udp without binding, which a lot of people do.

So I would believe strongly that this part of the code could be safely replaced with a bind().

**Comment by mint-dewit** [comment]
Closing in favour of https://github.com/nrkno/tv-automation-atem-connection/commit/b7be165ffd452ef05df0c1ea931322e6649cf6b1

**Pull request closed without merging**
