### PR TITLE
Addl macro commands and add MV window routing

### PR DESCRIPTION
**Pull request by krocheck**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds functionality for Macros

1. MacroPropertiesCommand - read only: (macroIndex, name, description, isUsed)
2. MacroRecordingStatusCommand - read only: (macroIndex, isRecording

Adds functionality for Multi Viewers
1. MultiViewerSourceCommand - read/write: (multiViewerId, windowIndex, source)

* **What is the current behavior?** (You can also link to an open issue here)
These commands did not exist

* **What is the new behavior (if this is a feature change)?**
Reads the name, description, use, and recording state of macros.  Reads & writes multi viewer window routes.

* **Other information**:
Tested as part of uncommitted changes to companion-module-atem.  Tested on TV Studio HD and Production Studio 4K 2ME

### CODE REVIEW

**Comment by krocheck** [comment]
@baltedewit and/or @Lange do you need me to do anything else to get this rolled in?  I'm holding changes to companion-module-atem since those are dependent on a new release here with these features.  Thanks!

**Comment by Lange** [comment]
Looks okay to me from a quick glance at the code. I don't have time to fire it up and test anything myself though. If @baltedewit is ok with it, I see no reason to delay merging.

**Comment by krocheck** [comment]
I'm trying to find a good way to post them here, but there's a couple videos showing this working in the Companion Slack #module-development channel.

**Comment by mint-dewit** [comment]
Hi! Thanks for the PR, that's awesome. I've done some quick changes to make the code align more with our current codebase.

The Macro stuff looks awesome, no changes needed. The state representation of the multiviewers felt a bit clumsy so I've changed it such that every multiviewer gets its own object with windows.

Before:
```
multiViewerSource: {
    1: { ... }
    [...]
    101: { ... ]
}
```

Has now become:
```
multiViewers: {
    '0': {
        '1': { ... }
        [ ... ]
    },
    '1': {
        '1': { ... }
        [ ... ]
    }
}
```

Furthermore I had to do some linting. If you do any future PR's it'd be great if you could run a quick `yarn ci` before opening.

**Comment by krocheck** [comment]
Copy all that.  Thanks!

**Comment by jesperstarkar** [comment]
Thank you @krocheck

**Pull request merged**
